flaskblog/comment/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired
from wtforms.fields.simple import TextAreaField, SubmitField

class CommentForm(FlaskForm):
    comment = TextAreaField('comment', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/posts/forms.py
from wtforms import StringField, SubmitField
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired
from wtforms.fields.simple import TextAreaField, MultipleFileField
from flask_wtf.file import FileAllowed

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    files_upload = MultipleFileField('Update Images', validators=[FileAllowed(['jpg', 'png', 'jpeg','mp4'])])
    submit = SubmitField('Post')
    
    
class UpdateForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/comment/routes.py
from flask import Blueprint, redirect, url_for, jsonify, request, render_template
import flaskblog

from flaskblog.models.ReplyModel import Reply
from flaskblog.reply.form import ReplyForm
from .forms import CommentForm
from flaskblog.models.PostModel import Post
from flaskblog.models.CommentModel import Comment
from flaskblog import db, logger
from flask_login import login_required, current_user
comment = Blueprint('comments', __name__)

@comment.route('/comment/<int:id>')
@login_required
def home_comment(id):
    post = Post.query.get_or_404(id)
    logger.info('User {} redirected to post {}'.format(current_user.get_id(), post.id))
    return redirect(url_for('posts.post'))


@comment.route('/comment/new/<int:post_id>', methods=['GET', 'POST'])
@login_required
def new_comment(post_id):
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(comment=form.comment.data, post_id=post_id, author_id=current_user.id)
        db.session.add(comment)
        db.session.commit()
        logger.info('user {} commented on {}'.format(current_user.get_id(), post_id))
        return redirect(url_for('posts.post', post_id=post_id))
    else:
        return redirect(url_for('main.home'))
    

@comment.route('/post/comment/<int:comment_id>', methods=['GET', 'POST'])
@login_required
def single_comment(comment_id):
    form = ReplyForm()
    comment = Comment.query.get_or_404(comment_id)
    page = request.args.get('page', 1, type=int)
    replies = Reply.query.filter_by(comment_id=comment_id).order_by(Reply.date.desc()).paginate(per_page=2,page=page)
    return render_template('comment.html',replies=replies , comment = comment, form =form)




@comment.route('/actioncomment/<int:comment_id>/<action>')
@login_required
def action_like(comment_id,action):
    comment = Comment.query.filter_by(id = comment_id).first_or_404()
    if action == "like":
        print("Like")
        current_user.like_comment(comment)
        db.session.commit()
    if action == 'unlike':
        print("Unlike")
        current_user.unlike_comment(comment)   
        db.session.commit()
    return redirect(request.referrer)

flaskblog/posts/routes.py
from ctypes import sizeof
from itertools import count
from flask import Blueprint, request, render_template, redirect, abort, url_for, flash
import os
from flaskblog.comment.forms import CommentForm
from flaskblog.models.CommentModel import Comment
from flaskblog.models.PostModel import Post
from flaskblog.posts.forms import PostForm, UpdateForm
from flaskblog import db, logger,app
from flask_login import current_user, login_required
from .utils import media, delete_post_images

posts = Blueprint('posts', __name__)

@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
    
        if len(form.files_upload.data) > 2:
            form.files_upload.data = None
            flash('Maximum of Images Exceeeded ', 'info')
            return render_template('create_post.html', title='New Post', form=form, legend='New Post')
        
        post = Post(title=form.title.data, content=form.content.data, author=current_user, images=None)
        db.session.add(post)
        db.session.commit()
    
        file_uploaded = str(form.files_upload.data)
        if file_uploaded.__contains__("image") or file_uploaded.__contains__("video"):
            if form.files_upload.data:
                file_names = media(form,post)
                post.images = file_names
                db.session.commit()
        flash(' Your post has been created ', 'success')
        logger.info('user {} created a new post with post id [{}]'.format(current_user.get_id(), post.id))
        return redirect(url_for('main.home'))
    else:
        return render_template('create_post.html', title='New Post', form=form, legend='New Post')


@posts.route('/post/<int:post_id>', methods=['GET', 'POST'])
@login_required
def post(post_id):
    form = CommentForm()
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    comments = Comment.query.filter_by(post_id=post_id).order_by(Comment.date.desc()).paginate(per_page=2,
      page=page)
    logger.debug('user {} route to post page with id [{}]'.format(current_user.get_id(), post.id))
    return render_template('post.html', title=post.title, post=post, comments=comments, form=form)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        logger.error('user {} cannot update post {}'.format(current_user.get_id(), post.id))
        abort(403)
    form = UpdateForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        logger.info('User {} successfully updated post {}'.format(current_user.get_id(), post.id))
        return redirect(url_for('posts.post', post_id=(post.id)))
    else:
        if request.method == 'GET':
            form.title.data = post.title
            form.content.data = post.content
        return render_template('update_post.html', title='Update Post', form=form, legend='Update Post')


@posts.route('/post/<int:post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        logger.error('user {} cannot delete post {}'.format(current_user.get_id(), post.id))
        abort(403)
    db.session.delete(post) 
    if post.images is not None:       
        delete_post_images(post.images)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    logger.info('user {} Successfully deleted post {}'.format(current_user.get_id(), post.id))
    return redirect(url_for('main.home'))

@posts.route('/actionpost//<action>/<int:post_id>')
@login_required
def action_like(action,post_id):
    post = Post.query.filter_by(id = post_id).first_or_404()
    if action == "like":
        current_user.like_post(post)
        db.session.commit()
    if action == 'unlike':
        current_user.unlike_post(post)
        db.session.commit()
    return redirect(request.referrer)

flaskblog/reply/routes.py
from flask import Blueprint, redirect, request, url_for
from .form import ReplyForm
from flaskblog.models.ReplyModel import Reply
from flaskblog import db, logger
from flask_login import login_required, current_user
reply = Blueprint('replies', __name__)

@reply.route('/reply/new/<int:comment_id>', methods=['GET', 'POST'])
@login_required
def new_reply(comment_id):
    form = ReplyForm()
    if form.validate_on_submit():
        reply = Reply(reply=form.reply.data, comment_id=comment_id, author_id=current_user.id)
        db.session.add(reply)
        db.session.commit()
        logger.info('user {} reply to comment {}'.format(current_user.get_id(), comment_id))
        return redirect(url_for('comments.single_comment', comment_id=comment_id))
    else:
        return redirect(url_for('main.home'))
    

@reply.route('/actionreply/<int:reply_id>/<action>')
@login_required
def action_like(reply_id,action):
    reply = Reply.query.filter_by(id = reply_id).first_or_404()
    if action == "like":
        print("Like")
        current_user.like_reply(reply)
        db.session.commit()
    if action == 'unlike':
        print("Unlike")
        current_user.unlike_reply(reply)   
        db.session.commit()
    return redirect(request.referrer)
    
    
    
    

flaskblog/users/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import current_user, login_required, logout_user, login_user
from flaskblog import db, bcrypt, logger,Cloud
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateForm, ResetPasswordForm, RequestRestForm, RequestVerifyForm
from flaskblog.models.UserModel import User
from flaskblog.models.PostModel import Post
from flaskblog.users.utils import send_reset_email, save_picture, send_login_notification_mail
users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data.lower(), password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f"Account Created for {form.username.data} !. Kindly verify your account", 'success')
        logger.info(f"New user {user.username} created with id {user.id}")
        return redirect(url_for('users.verify_request', mail=user.email))
    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user.verified != 1:
            flash(' Kindly verify your Account!', 'info')
            return redirect(url_for('users.verify_request', mail=user.email))
        if bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            if next_page:
                return redirect(next_page)
            flash('You are logged in !', 'success')
            logger.info('User {} with user id {} successfully logged In'.format(user.username, user.id))
            return redirect(url_for('main.home'))
        flash('Login Unsuccessful. Kindly Confirm your Username and Password!', 'danger')
        logger.error('User with email {} login unsuccessful'.format(form.email.data))
        logger.debug('User with email {} routed to login page'.format(form.email.data))
    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    user = current_user.get_id()
    logout_user()
    logger.info('User {} logout successfully'.format(user))
    return redirect(url_for('users.login'))


@users.route('/home/<string:username>')
@login_required
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    username = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=username).order_by(Post.date_posted.desc()).paginate(per_page=5,
      page=page)
    logger.info('User {} directed to users post'.format(username.id))
    return render_template('user_post.html', posts=posts, user=username)


@users.route('/verify_account', methods=['GET', 'POST'])
def verify_request():
    form = RequestVerifyForm()
    mail = request.args.get('mail')
    if mail:
        form.email.data = mail
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user.verified == 1:
            return redirect(url_for('users.login'))
        message_status = send_login_notification_mail(user)
        if message_status == 1:
            flash('An email has been sent to your email to verify your account', 'info')
            return redirect(url_for('users.login'))
        print(message_status)
        logger.info('Message sent to {} failed with error {}'.format(mail, message_status))
        flash('Email Failed! Retry verification again', 'danger')
        return redirect(url_for('users.verify_request', mail = mail))
    else:
        return render_template('verify.html', title='Account Verification', form=form)


@users.route('/verified/<token>')
def verify_token(token):
    user = User.verify_reset_token(token)
    if user is None:
        flash('Invalid or Expired token', 'warning')
        logger.error('User {} inpuuted an invalid or expired token'.format(current_user.get_id()))
        return redirect(url_for('users.verify_request'))
    else:
        user.verified = 1
        db.session.commit()
        flash('Your account has been verified and activated Successfully. Kindly login and explore', 'success')
        logger.info('User {} password successfuly updated'.format(current_user.get_id()))
        return redirect(url_for('users.login'))

@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    else:
        form = RequestRestForm()
        if form.validate_on_submit():
            user = User.query.filter_by(email=(form.email.data)).first()
            send_reset_email(user)
            flash('An email has been sent to your email to reset password', 'info')
            logger.info(' User {} successfully reset password'.format(user.id))
            return redirect(url_for('users.login'))
        return render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<token>')
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Invalid or Expired token', 'warning')
        logger.error('User {} inpuuted an invalid or expired token'.format(current_user.get_id()))
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated. Kindly login ', 'success')
        logger.info('User {} password successfuly updated'.format(current_user.get_id()))
        return redirect(url_for('users.login'))
    else:
        return render_template('reset_token.html', title='Reset Password', form=form)


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateForm()
    if form.validate_on_submit():
        if form.picture.data:
            Cloud.destroy(current_user.image_file.split(".")[2].split("/")[-1])
            image = save_picture(form.picture.data)
            current_user.image_file = image
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your Information was Successfully Updated ', 'success')
        logger.info('user {} information successfully updated'.format(current_user.get_id()))
        return redirect(url_for('users.account'))
    else:
        if request.method == 'GET':
            form.username.data = current_user.username
            form.email.data = current_user.email
        return render_template('account.html', title='Account', form=form)

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class = 'content-section' style="background: #1d2124;">
        <form method = "POST", action = ''>
        {{form.hidden_tag()}}  
        <fieldset class = "form-group">
              <legend class ="border-bottom mb-4" style="color:#cfdde3"> Login </legend>
              
              <div class = "form-group" style="color:#cfdde3">
                  {{form.email.label(class = "form-control-label")}} 

                     {% if form.email.errors %}
                        {{ form.email(class = "form-control form-control-lg is-invalid")}}
                            <div class = "invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span> {{error}} </span>
                                {% endfor %}
                            </div>
                        {% else%}
                            {{ form.email(class = "form-control form-control-lg")}}
                        {% endif %}                   
              </div>

              <div class = "form-group" style="color:#cfdde3">
                  {{form.password.label(class = "form-control-label")}}

                     {% if form.password.errors %}
                        {{ form.password(class = "form-control form-control-lg is-invalid")}}
                            <div class = "invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span> {{error}} </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class = "form-control form-control-lg")}}
                        {% endif %}                   
              </div>
              <div class = "form-check" style="color:#cfdde3">
                     
                     {{form.remember(class = "form-check-input")}}
                     {{form.remember.label(class = "form-check-label")}}
              </div>
        </fieldset>
        <div class = "form-group" style="color:#cfdde3"> 
           {{form.submit(class = "btn btn-outline-info")}}
           <small class ="text-muted ml-2">
               <a href ="{{url_for('users.reset_request')}}"> Forget password ?</a>
        </small>
        </div>
        
        </form>
    </div>
    <div class ="border-top pt-3">
       <small class = "text-muted">
            New User? <a class = "ml-2" href ="{{url_for('users.register')}}" > Sign Up  </a>
       </small>
     </div>
{% endblock content %}

flaskblog/templates/post.html
{% extends "layout.html" %}

<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">

{% block content %}
<article class="media content-section" style="background: #1d2124;">
  <img class="rounded-circle article-img"
    src="{{post.author.image_file }}">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" 
      href="{{url_for('users.user_posts',username=post.author.username)}}">{{ post.author.username }}</a>
      <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
      {% if post.author == current_user %}
      <div>
        <a class="btn btn-secondary btn-sm mt-1 mb-1"
          href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal"
          data-target="#deleteModal">Delete</button>
      </div>
      {% endif %}
    </div>
    <h2 class="article-title" style="color: #cfdde3;">{{ post.title }}</h2>
    <p class="article-content" style="color: #e3d1d1;">{{ post.content }}</p>


    {% if post.images is not  none %}
      


    {% if post.images| count == 1 %}
      {% for media in post.images %}
      <center> 
        {%if media.endswith("mp4")%}
        <div class="center">
          <a href="{{ media}}"  target="_blank"> 
            <video width="300" height="250" autoplay muted loop controls>
                <source src="{{ media}}" type="video/mp4">
                <source src="{{ media}}" type="video/ogg">
            </video>
          </a>
        </div>

        {%else%}
        <div  class="center">
          <div class="column">
            <a href="{{media}}"  target="_blank"> <img src="{{media}}" alt="Snow" style="width:250;height:200;" class="responsive"></a>
          </div>
        </div>

        {%endif%}

      </center>
      {%endfor%}
    {% endif %}


    {% if post.images| count == 2 %}
      <div class="row" class="center">
          {% for media in post.images %}
            {%if media.endswith("mp4")%}
              <div class="column">
                <a href="{{ media}}"  target="_blank"> <video width="250" height="300" autoplay muted loop controls>
                  <source src="{{ media}}" type="video/mp4">
                  <source src="{{ media}}" type="video/ogg">
                </video></a>
              </div>

            {%else%}
                
                  <div class="column">
                    <a href=" {{media}}" target="_blank"> <img src="{{media}}" alt="Snow" style="width:250px;height:300px;object-fit:cover;"></a>
                  </div>
               
            {%endif%}
          {%endfor%}

      </div>
    {% endif %}

{% endif %}


<br>


<br>
<div style="display: flex;">
  <div style="display: flex; ">
    &nbsp; &nbsp; &nbsp; &nbsp;<h5><img src="{{url_for('static', filename ='imagefolder/like.png')}}" alt="Snow" style="width:40px;height:40px;padding:0px" align:right> &nbsp;<h2>{{current_user.post_number_of_likes(post)}}</h2>

  </div>

  <div style="display: flex;">
    <h5><img src="{{url_for('static', filename ='imagefolder/comment.png')}}" alt="Snow" style="width:40px;height:40px;padding:0px">&nbsp;<h2>{{current_user.number_of_comments(post)}}</h2>

  </div>
</div>

            
<br> 
             {%if current_user.has_liked_post(post)%}

            <div class="btn-toolbar pull-left">
              <a href="{{url_for('posts.action_like', post_id=post.id, action = 'unlike')}}"> <button  class="btn mr-3 btn-secondary btn-sm like" memberid = {{post.id}}><i class="fa fa-thumbs-up">  Unlike  </i> </button></a>
             <a href="{{url_for('posts.post', post_id=post.id)}}"> <button class="btn mr-3 btn-sm btn-dark"><i class="fa fa-commenting-o">Comment</i> </button></a>
          </div>

          {%else%}
             
          <div class="btn-toolbar pull-left">
            <a href="{{url_for('posts.action_like', post_id=post.id, action = 'like')}}"> <button  class="btn mr-3 btn-primary btn-primary btn-sm like" memberid = {{post.id}}><i class="fa fa-thumbs-up">  Like  </i> </button></a>
           <a href="{{url_for('posts.post', post_id=post.id)}}"> <button class="btn mr-3 btn-sm btn-dark"><i class="fa fa-commenting-o">Comment</i> </button></a>
        </div>

          {%endif%}
</article>
<h2 style="color: #cfdde3;">Comments</h2>
<article class="media content-section" style="background: #1d2124;" >
  <div class="container mt-1">
    <div class="d-flex justify-content-start row">
      <div class="col-md-8">

{% if comments.total > 0 %}
      {% for comment in comments.items %}
        <div class="d-flex flex-column comment-section">
          <div class="bg-#1d2124 p-2">
            <div class="d-flex flex-row user-info">
              <img class="rounded-circle"
                src="{{ comment.comment_author.image_file }}" width="40">
              <div class="d-flex flex-column justify-content-start ml-2">
              {% if comment.author_id.username == current_user.username%}
                 <span class="d-block font-weight-bold name" style="color: #cfdde3;">author-{{comment.author_id.username}}</span>
              {%else%}
               <span class="d-block font-weight-bold name" style="color: #cfdde3;">{{comment.author_id.username}}</span>
              {%endif%}
                <small class="date text-black-50" style="color: #cfdde3;">Public - {{ comment.date.strftime('%Y-%m-%d %H:%M') }}</small>
              </div>
            </div>
            <div class="mt-2">
             <span><a class="article-title" href="{{url_for('comments.single_comment', comment_id = comment.id)}}">  <p class="comment-text" style="color: #cfdde3;">{{comment.comment}}</p></a></span> 
            </div>
          </div>
          <br>

          <div style="display: flex;">
            <div style="display: flex; ">
              <h5><img src="{{url_for('static', filename ='imagefolder/like.png')}}" alt="Snow" style="width:30px;height:30px;padding:0px" align:right>&nbsp;<h3>{{current_user.comment_number_of_likes(comment)}}</h3>
          
            </div>
          
            <div style="display: flex;">
      &nbsp; &nbsp; &nbsp; &nbsp; <h5><img src="{{url_for('static', filename ='imagefolder/comment.png')}}" alt="Snow" style="width:25px;height:30px;padding:0px">&nbsp; <h3>{{current_user.number_of_reply_for_comment(comment)}}</h3>
          
            </div>
          </div>
          
                      
          <br> 
                       {%if current_user.has_liked_comment(comment)%}
          
                       
                       
          
                      <div class="btn-toolbar pull-left">
                        <a href="{{url_for('comments.action_like', comment_id=comment.id, action = 'unlike')}}"> <button  class="btn mr-3 btn-secondary btn-sm like" memberid = {{post.id}}><i class="fa fa-thumbs-up">  Unlike  </i> </button></a>
                        <a class="article-title" href="{{url_for('comments.single_comment', comment_id = comment.id)}}"> <button class="btn mr-3 btn-dark"><i class="fa fa-commenting-o">Replies({{current_user.number_of_reply_for_comment(comment)}})</i> </button></a>
                    </div>
          
                    {%else%}
                       
                    <div class="btn-toolbar pull-left">
                      <a href="{{url_for('comments.action_like', comment_id=comment.id, action = 'like')}}"> <button  class="btn mr-3 btn-primary btn-sm like" memberid = {{post.id}}><i class="fa fa-thumbs-up">  Like  </i> </button></a>
                      <a class="article-title" href="{{url_for('comments.single_comment', comment_id = comment.id)}}"> <button class="btn mr-3 btn-sm btn-dark"><i class="fa fa-commenting-o">Replies({{current_user.number_of_reply_for_comment(comment)}})</i> </button></a>
                  </div>
          
                    {%endif%}









        </div>
        <br>
          {%endfor%}


          {% else %}
          <br>
          <br>
          <br>
          <h2 style="color: #cfdde3;">  No Comment made yet </h2>
      
          {% endif %}

         

        



      


        <div class="bg-#1d2124 p-2" style="background-color: #1d2124;">
          <form method="POST" , action="{{ url_for('comments.new_comment', post_id=post.id) }}">
            {{form.hidden_tag()}}
            <fieldset class="form-group">
              <div class="d-flex flex-row align-items-start">
                <img class="rounded-circle"
                  src="{{ current_user.image_file }}" width="40">
                {{form.comment.label(class = "form-control-label " )}}
                <style>
                  .form-control-label {color: #cfdde3;}
               </style>

                {% if form.comment.errors %}
                {{ form.comment(class = "form-control form-control-lg is-invalid text-#cfdde3")}}
                <div class="invalid-feedback">
                  {% for error in form.comment.errors %}
                  <span> {{comment}} </span>
                  {% endfor %}
                </div>
                {% else%}
                {{ form.comment(class = "form-control ml-1 shadow-none textarea color-black")}}
                
                {% endif %}
              </div>
              <div class="mt-2 text-right">
                {{form.submit(class="btn btn-primary btn-sm shadow-none",id = "postcomment")}}

              </div>



            </fieldset>

          </form>

        {% for page_num in comments.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if comments.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('posts.post', post_id = post.id,page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('posts.post', post_id = post.id,page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}

        </div>










      </div>
    </div>
  </div>
</article>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
          <input class="btn btn-danger" type="submit" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

flaskblog/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class = 'content-section'  style="background: #1d2124;">
        <form method = "POST", action = ''>
        {{form.hidden_tag()}}  
        <fieldset class = "form-group" >
              <legend class ="border-bottom mb-4" style="color:#cfdde3">Reset Pasword </legend>
              <div class = "form-group" style="color:#cfdde3">
                  {{form.email.label(class = "form-control-label")}} 

                     {% if form.email.errors %}
                        {{ form.email(class = "form-control form-control-lg is-invalid")}}
                            <div class = "invalid-feedback" style="color:#cfdde3">
                                {% for error in form.email.errors %}
                                    <span> {{error}} </span>
                                {% endfor %}
                            </div>
                        {% else%}
                            {{ form.email(class = "form-control form-control-lg")}}
                        {% endif %}                   
              </div>

        </fieldset>
        <div class = "form-group" style="color:#cfdde3"> 
           {{form.submit(class = "btn btn-outline-info")}}
        </div>
        </form>
    </div>
{% endblock content %}